server:
  port: 8081


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
      routes:
        - id: learning-outcomes
          uri: http://localhost:8080
          predicates:
            - Path=/learningOutcomes, /learningOutcomes/{learningOutcomeId}
        - id: learning-spaces
          uri: http://localhost:8080
          predicates:
            - Path=/learningSpaces, /learningSpaces/{learningSpaceId}, /learningSpaces/{learningSpaceId}/**
        - id: courses
          uri: http://localhost:8080
          predicates:
            - Path=/courses, /courses/{courseId}, /courses/{courseId}/**

# Eureka
eureka:
  client:
    enabled: false
