version: '3.4'
services:
  springcloud-gateway:
    image: docker.nexus.archi-lab.io/archilab/coalbase-api-gateway
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS="-Xms128m -Xmx256m"
    networks:
      - coalbase_backend
networks:
  coalbase_backend:
    external: true
