version: '3.4'

services:
  coalbase_api_gateway:
    image: docker.nexus.archi-lab.io/archilab/coalbase-learning-outcome
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
    networks:
      - coalbase_backend
networks:
  coalbase_backend:
    external: true
